import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/src/components/Navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="vsc-initialized">
        <Navbar>
          {children}
        </Navbar>
      </body>
    </html>
  );
}
